import type { Entitlement, Permission, Role } from '@barberos/contracts';

export type AccessProfileKey = 'superAdmin' | 'admin' | 'user' | 'barber';

export type AccessProfile = {
  key: AccessProfileKey;
  label: string;
  role: Role;
  description: string;
};

export const accessProfiles: Record<AccessProfileKey, AccessProfile> = {
  superAdmin: {
    key: 'superAdmin',
    label: 'Super Admin',
    role: 'PLATFORM_MASTER',
    description: 'Administra a plataforma BarberOS, tenants, assinaturas e suporte.',
  },
  admin: {
    key: 'admin',
    label: 'Admin da barbearia',
    role: 'OWNER',
    description: 'Dono da barbearia com acesso total ao tenant, filiais, equipe e financeiro.',
  },
  user: {
    key: 'user',
    label: 'Recepcionista',
    role: 'RECEPTIONIST',
    description: 'Opera agenda, clientes, comandas, pagamentos, caixa e estoque do dia a dia.',
  },
  barber: {
    key: 'barber',
    label: 'Barbeiro',
    role: 'PROFESSIONAL',
    description: 'Acompanha propria agenda, clientes permitidos, producao, comissoes e repasses.',
  },
};

const operationalPermissions = [
  'dashboard.read',
  'appointments.read',
  'appointments.create',
  'appointments.update',
  'appointments.cancel',
  'professionals.read',
  'professionals.create',
  'professionals.update',
  'services.read',
  'services.create',
  'services.update',
  'schedules.read',
  'schedules.manage',
  'customers.read',
  'customers.create',
  'customers.update',
  'appointments.check_in',
  'orders.read',
  'orders.create',
  'orders.update',
  'orders.item.add',
  'orders.item.update',
  'orders.item.remove',
  'payments.receive',
  'payments.refund',
  'cash.open',
  'cash.withdraw',
  'cash.close',
  'finance.read',
  'finance.write',
  'commission.read',
  'commission.manage',
  'inventory.read',
  'inventory.write',
  'worker.failures.read',
  'notifications.status.read',
  'settings.read',
  'memberships.read',
  'memberships.manage',
  'audit.read',
] as const satisfies readonly Permission[];

export const rolePermissions: Record<Role, readonly Permission[]> = {
  PLATFORM_MASTER: operationalPermissions,
  PLATFORM_SUPPORT: [
    'dashboard.read',
    'appointments.read',
    'professionals.read',
    'services.read',
    'schedules.read',
    'customers.read',
    'settings.read',
    'audit.read',
    'worker.failures.read',
    'notifications.status.read',
  ],
  OWNER: operationalPermissions,
  MANAGER: [
    'dashboard.read',
    'appointments.read',
    'appointments.create',
    'appointments.update',
    'appointments.cancel',
    'professionals.read',
    'professionals.create',
    'professionals.update',
    'services.read',
    'services.create',
    'services.update',
    'schedules.read',
    'schedules.manage',
    'customers.read',
    'customers.create',
    'customers.update',
    'appointments.check_in',
    'orders.read',
    'orders.create',
    'orders.update',
    'orders.item.add',
    'orders.item.update',
    'orders.item.remove',
    'payments.receive',
    'inventory.read',
    'inventory.write',
    'worker.failures.read',
    'notifications.status.read',
    'settings.read',
  ],
  FINANCE: [
    'dashboard.read',
    'finance.read',
    'finance.write',
    'cash.open',
    'cash.withdraw',
    'cash.close',
    'commission.read',
    'commission.manage',
    'payments.receive',
    'payments.refund',
  ],
  RECEPTIONIST: [
    'dashboard.read',
    'appointments.read',
    'appointments.create',
    'appointments.update',
    'appointments.cancel',
    'professionals.read',
    'services.read',
    'schedules.read',
    'customers.read',
    'customers.create',
    'customers.update',
    'appointments.check_in',
    'orders.read',
    'orders.create',
    'orders.update',
    'orders.item.add',
    'orders.item.update',
    'orders.item.remove',
    'payments.receive',
    'cash.open',
    'cash.close',
    'finance.read',
    'inventory.read',
    'notifications.status.read',
  ],
  PROFESSIONAL: [
    'dashboard.read',
    'appointments.read',
    'professionals.read',
    'services.read',
    'schedules.read',
    'customers.read',
    'orders.read',
    'commission.read',
  ],
};

export const roleEntitlements: Record<Role, readonly Entitlement[]> = {
  PLATFORM_MASTER: [
    'core.operations',
    'finance',
    'inventory',
    'worker.operations',
    'notifications',
    'ai',
  ],
  PLATFORM_SUPPORT: ['core.operations', 'worker.operations', 'notifications'],
  OWNER: ['core.operations', 'finance', 'inventory', 'worker.operations', 'notifications', 'ai'],
  MANAGER: ['core.operations', 'inventory', 'worker.operations', 'notifications'],
  FINANCE: ['core.operations', 'finance'],
  RECEPTIONIST: ['core.operations', 'finance', 'inventory', 'notifications'],
  PROFESSIONAL: ['core.operations', 'finance'],
};
