import type { SessionContext } from '@barberos/contracts';

export const developmentSession: SessionContext = {
  authState: 'authenticated',
  userId: 'dev-user',
  email: 'dev@barberos.local',
  tenantId: 'dev-tenant',
  membershipId: 'dev-membership',
  role: 'OWNER',
  permissions: [
    'dashboard.read',
    'appointments.read',
    'appointments.create',
    'appointments.update',
    'appointments.cancel',
    'professionals.read',
    'professionals.create',
    'professionals.update',
    'services.read',
    'services.create',
    'services.update',
    'schedules.read',
    'schedules.manage',
    'customers.read',
    'customers.create',
    'customers.update',
    'finance.read',
    'settings.read',
    'memberships.manage',
  ],
  entitlements: ['core.operations', 'finance'],
  branchScope: ['dev-branch', 'dev-branch-north'],
  activeBranchId: 'dev-branch',
  userName: 'Luan Ribeiro',
  tenantName: 'Barbearia Modelo',
  branchName: 'Unidade Centro',
  availableWorkspaces: [
    {
      tenantId: 'dev-tenant',
      tenantName: 'Barbearia Modelo',
      branchId: 'dev-branch',
      branchName: 'Unidade Centro',
    },
    {
      tenantId: 'dev-tenant',
      tenantName: 'Barbearia Modelo',
      branchId: 'dev-branch-north',
      branchName: 'Unidade Norte',
    },
  ],
};
